defaults:
  - _self_
  - preset: dev

hydra:
  job:
    chdir: false

evaluate:
  model1: ???
  model2: ???
  num_opened_moves: 1
  number_of_games: 64
  batch_size: 64
  temperature: 0.7
  temperature_decay: 0.7
  plot_board: false

interactive:
  model: 11_2w4_2000
  switch: true
  gui_radius: 50
  dark_mode: false
  temperature: 0.0
  temperature_decay: 1.0
