# @package _global_
model:
  board_size: 3
  layers: 2
  intermediate_channels: 5
  reach: 1
  switch_model: false
  rotation_model: true
  model_name: 3_2l_5c

data:
  num_train_samples: 1000
  num_val_samples: 100
  batch_size: 32
  noise: "none"
  noise_parameters: [3.0, 0.5, 1.0]
  temperature: 0.67
  temperature_decay: 1.0
  gamma: 0.0
  gamma_max: 25

train:
  epochs: 1
  batch_size: 32
  optimizer: adam
  learning_rate: 0.0001
  momentum: 0.9
  weight_decay: 0.0
  print_loss_frequency: 1000

elo:
  number_of_games: 16
  batch_size: 16
  num_opened_moves: 1
  temperature: 0.0
  temperature_decay: 0.7
  plot_board: false
  max_num_opponents: 3

vs_reference:
  batch_size: 32
  num_games: 256
  num_opened_moves: 1
  temperature: 0.0
  temperature_decay: 0.0
  plot_board: false

puzzle:
  board_size: 3
  num_samples: 1000

rst:
  start_index: 0
  num_iterations: 2
  num_data_models: 2
  load_initial_data: false
  save_data: false
